versions:
  "1.6.0":
    released_at: 2026-01-25T14:30:00Z
    matchers:
      - matcher_type: default
        severity: green
  "1.7.0":
    released_at: 2026-01-29T09:00:00Z
    notes: Development release with experimental features.
    matchers:
      - matcher_type: default
        severity: green

