versions:
  "2.0.0":
    released_at: 2026-01-22T10:30:00Z
    notes: Stable release.
    matchers:
      - matcher_type: default
        severity: green
  "2.1.0":
    released_at: 2026-01-28T10:00:00Z
    notes: Development release for testing new features.
    matchers:
      - matcher_type: default
        severity: green

