versions:
  "2.1.0":
    released_at: 2026-01-28T10:00:00Z
    matchers:
      - matcher_type: default
        severity: green
  "2.2.0":
    released_at: 2026-01-30T15:00:00Z
    notes: Test release for internal testing.
    matchers:
      - matcher_type: default
        severity: green

